os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - libbz2-dev
    - libssl-dev
    - gcc-5
    - g++-5
    - libeigen3-dev

cache:
  directories:
    - $HOME/boost_1_61_0/boost
    - $HOME/boost_1_61_0/stage/lib
    - $HOME/eigen_3_2_9
    - $HOME/eigen_3_2_9/install
    - $HOME/opencv_3_1/opencv
    - $HOME/opencv_3_1/opencv_contrib
    - $HOME/opencv_3_1/stage/lib

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - sudo apt-get install python-dev python-numpy
  - chmod +x tools/travis/install_eigen.sh
  - tools/travis/install_eigen.sh
  - chmod +x tools/travis/install_opencv.sh
  - tools/travis/install_opencv.sh
  - chmod +x tools/travis/install_boost.sh
  - tools/travis/install_boost.sh

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DBOOST_ROOT=~/boost_1_61_0 -DTRAVIS_EIGEN_DIRECTORY=~/eigen_3_2_9/install/include -DTRAVIS=YES
  - make
  - ctest --output-on-failure